export interface Quote {
  text: string;
  author: string;
}

export const quotes: Quote[] = [
  { text: '学而时习之，不亦说乎。', author: '孔子' },
  { text: '千里之行，始于足下。', author: '老子' },
  { text: '业精于勤，荒于嬉；行成于思，毁于随。', author: '韩愈' },
  { text: '不积跬步，无以至千里；不积小流，无以成江海。', author: '荀子' },
  { text: '书山有路勤为径，学海无涯苦作舟。', author: '韩愈' },
  { text: '知之者不如好之者，好之者不如乐之者。', author: '孔子' },
  { text: '三人行，必有我师焉。', author: '孔子' },
  { text: '温故而知新，可以为师矣。', author: '孔子' },
  { text: '莫等闲，白了少年头，空悲切。', author: '岳飞' },
  { text: '宝剑锋从磨砺出，梅花香自苦寒来。', author: '佚名' },
  { text: '天才就是百分之九十九的汗水加百分之一的灵感。', author: '爱迪生' },
  { text: '成功不是最终的目的，失败也不是致命的，重要的是继续前进的勇气。', author: '丘吉尔' },
  { text: '知识就是力量。', author: '培根' },
  { text: '想象力比知识更重要。', author: '爱因斯坦' },
  { text: '生活中最重要的事情不是我们在哪里，而是我们朝着什么方向前进。', author: '奥利弗·温德尔·霍姆斯' },
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: '成功就是把复杂的事情简单地做，把简单的事情重复做。', author: '佚名' },
  { text: '最大的敌人不是别人，而是昨天的自己。', author: '佚名' },
  { text: '每一次努力，都是未来某个惊喜的铺垫。', author: '佚名' },
  { text: '学习是灯，努力是油；要想灯亮，必须加油。', author: '佚名' },
  { text: '世上无难事，只要肯登攀。', author: '毛泽东' },
  { text: '路漫漫其修远兮，吾将上下而求索。', author: '屈原' },
  { text: '读书破万卷，下笔如有神。', author: '杜甫' },
  { text: '黑发不知勤学早，白首方悔读书迟。', author: '颜真卿' },
  { text: '少壮不努力，老大徒伤悲。', author: '汉乐府' },
  { text: '一天不练自己知道，两天不练同行知道，三天不练观众知道。', author: '佚名' },
  { text: '自律给我自由。', author: '佚名' },
  { text: '你的时间有限，不要浪费时间活在别人的生活里。', author: '乔布斯' },
  { text: '种一棵树最好的时间是十年前，其次是现在。', author: '非洲谚语' },
  { text: '水滴石穿，非一日之功。', author: '佚名' },
  { text: '今日事，今日毕。', author: '佚名' },
  { text: 'Every expert was once a beginner.', author: 'Helen Hayes' },
  { text: 'Small daily improvements over time lead to stunning results.', author: 'Robin Sharma' },
];
